### ISSUE TITLE
Upgrading to 0.12.0 causes everything to break

### ISSUE THREAD

**Issue by Daniel-Glucksman** [grofit/treacherous-aurelia#10]
Errors don't display anymore on validate

Poor documentation as to what's changed

Using Validation Summary causes a js error

**Comment by grofit** [comment]
The provided example says otherwise:

https://rawgit.com/grofit/treacherous-aurelia/master/examples/index.html

The changes for the most part do not effect end users, you can check the treacherous page for core changes, if you can provide information on your error then hopefully someone can look at it.

As far as general documentation goes for the non-core treacherous module my time is limited at the moment, I have brought @jsobell onboard to try and improve this stuff as he works a lot with the aurelia community, I rarely deal with them/it at the moment, however the docs on the treacherous page should be fine and the example here is updated every release to reflect latest changes.

https://github.com/grofit/treacherous/blob/master/docs/breaking-changes.md

I would assume your issue is down to you not using the new builder approach (`createGroup` returns a builder now, not an actual group), in which case your issue is actually with treacherous not treacherous-aurelia, if this is not the case hopefully your errors will shed some light on it.

Feel free to add some docs yourself if you want.

**Comment by grofit** [comment]
Assuming this is no longer an issue, although there may be other issues given the amount of changes in treacherous since this was raised.
