### ISSUE TITLE
Child objects and .addRuleSetForEach()

### ISSUE THREAD

**Issue by TimBailey-pnk** [grofit/treacherous-aurelia#14]
Hi, struggling to get this to work for child objects....
```
    this.model = {
      name: '',
      contacts: [{
        fname: '',
        lname: '',
        email: ''
      }]
    }
```
First issue I had, and fixed is that the validationGroup "location" inside `validate-binding-behaviour` cant find the validationGroup for the child object (instance in contacts array).  I fixed this like this....

```
if (this._isWithinChildBinding(overrideContext.overrideContext)) {
     console.log('..fixup validationGroup')
     treacherousState.validationGroup = overrideContext.overrideContext.parentOverrideContext.bindingContext.validationGroup
}
```

But now I'm having a problem where the validationPredicate cant find the property, this is because `treacherousState.propertyName` is 'fname', but the x.property is (correctly?) `contacts[0].fname`.

So i'm wondering, given an `binding` can i find the matching path-name so that the predicate will match

Regards
Tim

**Comment by grofit** [comment]
Hey, this version was stuck until dynamic attributes were available in aurelia (not sure if that has happened yet), so the version of treacherous being used in this version may be quite old, but that aside I think there was some attribute you could provide to indicate what the property was if you needed to override it.

Upon looking at the docs it looks like if you do `validate-property="your.property[1].stuff.here"` you may be ok as it will use that override instead of trying to auto generate it. There is a new version which was almost complete which bypassed some of these issues by using the treacherous-view library but there was some problems getting aurelia view/vm data into standard html attributes, so until that is fixed the new version is on hold and has been for about 8 months now I think.

**Comment by grofit** [comment]
#12 is potentially still blocked so closing this one until the other one is fixed, feel free to re-raise if needed.
